# Generated by Django 2.2.2 on 2019-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
