# Generated by Django 2.2.2 on 2019-08-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='desc',
            field=models.TextField(default='بدون توضیحات'),
        ),
    ]
