# Generated by Django 2.2.2 on 2019-08-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20190827_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.IntegerField(),
        ),
    ]
