# Generated by Django 2.2.2 on 2019-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20190707_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banks',
            name='name_bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='self'),
        ),
    ]
