# Generated by Django 2.2.5 on 2019-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_transactions_firstload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='firstLoad',
            field=models.BooleanField(default=True),
        ),
    ]
