# Generated by Django 2.2.5 on 2019-10-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20191001_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='firstLoad',
        ),
        migrations.AddField(
            model_name='user',
            name='firstLoad',
            field=models.BooleanField(default=True),
        ),
    ]
